[package]
name = "nexa-verifier"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Vérification on-chain d'une preuve Groth16 du circuit NEXA pour.circom"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
solana-program = "2.1"
groth16-solana = "0.1"

[dev-dependencies]
mollusk-svm = "0.1"
solana-sdk = "2.1"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
